version: '3.8'
services:
  gateway:
    build: ./gateway
    restart: always
    depends_on:
      - rabbit
    container_name: gateway
    ports:
      - '7000:7000'

  app-server:
    build: ./app-server
    restart: always
    depends_on:
      - rabbit
      - postgis
    container_name: app-server
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://backend_postgis_1:5432/proyectodb"
      - "SPRING_DATASOURCE_USERNAME=unimap"
      - "SPRING_DATASOURCE_PASSWORD=adminunimap123"
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"

  rabbit:
    image: "rabbitmq"
    container_name: rabbit
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"

  geoserver:
    image: kartoza/geoserver:2.16.2
    depends_on:
      - postgis
    ports:
      - "8080:8080"
    environment:
      - "SAMPLE_DATA=true"
    volumes:
      - geoserverdata:/opt/geoserver/data_dir

  postgis:
      image: kartoza/postgis:9.6-2.4
      ports:
        - "25432:5432"
      command: echo "host    all             all             0.0.0.0/0            md5" >> /etc/postgresql/9.6/main/pg_hba.conf && service postgresql restart
      environment:
        - "POSTGRES_USER=unimap"
        - "POSTGRES_PASS=adminunimap123"
        - "POSTGRES_DBNAME=proyectodb"
        - "DEFAULT_ENCODING=UTF8"
      volumes:
        - dbdata:/var/lib/postgresql

volumes:
    geoserverdata:
      external: true
    dbdata:
      external: true
