spring:
  application:
    name: gateway
  #RabbitMQ Configuration Properties
  rabbitmq:
    host: rabbit
    password: guest
    port: 5672
    username: guest

#Tomcat Embedded Server Configuration
server:
  port: 7000

#Zuul Configuration Properties
zuul:
  routes:
    app-server:
      path: app-server/**
      serviceId: app-server
    rabbit:
      path: api/**
      serviceId: gateway

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
