spring:
  application:
    name: gateway
  #RabbitMQ Configuration Properties
  rabbitmq:
    addresses: rabbit://guest:guest@rabbit:5672/
    host: 172.20.0.2
    port: 5672
    password: guest
    username: guest

#Tomcat Embedded Server Configuration
server:
  port: 7000
