spring:
  application:
    name: gateway
  #RabbitMQ Configuration Properties
  rabbitmq:
    host: rabbit
    port: 5672
    password: guest
    username: guest

#Tomcat Embedded Server Configuration
server:
  port: 7000
