spring:
  application:
    name: app-server
  #RabbitMQ Configuration Properties
  rabbitmq:
    host: rabbit
    port: 5672
    password: guest
    username: guest
  profiles:
    active: configuration, receiver

#Tomcat Embedded Server Configuration
server:
  port: 8001
