spring:
  application:
    name: app-server
  #RabbitMQ Configuration Properties
  rabbitmq:
    host: rabbit
    port: 5672
    password: guest
    username: guest
  profiles:
    active: configuration, receiver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://backend_postgis_1:5432/proyectodb
    #url: jdbc:postgresql://localhost:25432/proyectodb
    username: unimap
    password: adminunimap123
    driver-class-name: org.postgresql.Driver

#Tomcat Embedded Server Configuration
server:
  port: 8001
