spring:
  application:
    name: app-server
  #RabbitMQ Configuration Properties
  rabbitmq:
    addresses: localhost:5672
    password: guest
    username: guest

#Tomcat Embedded Server Configuration
server:
  port: 8001