spring:
  application:
    name: app-server
  #RabbitMQ Configuration Properties
  rabbitmq:
    host: rabbit
    password: guest
    port: 5672
    username: guest
    virtualhost: /

#Tomcat Embedded Server Configuration
server:
  port: 8001

#Eureka Configuration Properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka